# Generated by Django 2.2.10 on 2020-03-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200316_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='titles',
        ),
        migrations.AddField(
            model_name='item',
            name='titles',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='core.category'),
            preserve_default=False,
        ),
    ]
