# Generated by Django 2.2.10 on 2020-03-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200316_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Sub_category',
        ),
    ]
