# Generated by Django 2.2.10 on 2020-03-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200316_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='SubCategory',
            field=models.ForeignKey(default=True, max_length=100, on_delete=django.db.models.deletion.CASCADE, to='core.SubCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
