# Generated by Django 2.2.10 on 2020-03-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_contact_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_de',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='category_en',
            field=models.ForeignKey(max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
