# Generated by Django 2.2.10 on 2020-03-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200320_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category_de',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title_en',
        ),
    ]
