# Generated by Django 2.2.10 on 2020-03-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200320_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_ar',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
