# Generated by Django 2.2.10 on 2020-03-22 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_category_category_ar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'category_ar'},
        ),
    ]
