# Generated by Django 2.2.10 on 2020-03-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200322_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_ar',
        ),
    ]
