# Generated by Django 2.2.10 on 2020-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_category_category_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_arabic',
            field=models.CharField(default=True, max_length=20),
            preserve_default=False,
        ),
    ]
