# Generated by Django 2.2.10 on 2020-03-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_category_category_arabic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_arabic',
        ),
    ]
