# Generated by Django 2.2.10 on 2020-03-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_category_category_arabic'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_ar',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_en',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
