# Generated by Django 2.2.10 on 2020-03-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200324_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category_ar',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category_en',
        ),
    ]
