# Generated by Django 2.2.10 on 2020-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200324_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_ar',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
