# Generated by Django 2.2.10 on 2020-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200324_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price_ar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price_en',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label_ar',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label_en',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_ar',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price_en',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug_ar',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug_en',
            field=models.SlugField(null=True),
        ),
    ]
