# Generated by Django 2.2.10 on 2020-03-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200324_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='title_contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('title_en', models.CharField(max_length=20, null=True)),
                ('title_ar', models.CharField(max_length=20, null=True)),
                ('subtitle', models.CharField(max_length=20)),
                ('subtitle_en', models.CharField(max_length=20, null=True)),
                ('subtitle_ar', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
