# Generated by Django 2.2.10 on 2020-03-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_contact_form_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_form',
            name='Upload',
        ),
    ]
